services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/static/pdf:/app/pdf
      - ./front/public/pdf:/app/front-pdf
    networks:
      - app-network
    environment:
      - PDF_STORAGE_DIR=/app/pdf
      - FRONT_PUBLIC_DIR=/app/front-pdf

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./src/main/resources/static/pdf:/usr/share/nginx/html/pdf
    networks:
      - app-network
    env_file:
      - ./front/.env

networks:
  app-network:
    driver: bridge
